title: ZhangZ's Blog
description: Personal blog
url: https://deciding.github.io
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

author:
  name: Dr. Zhang Zining
  title: Singapore
  tags: LLM, HPC, CUDA Kernel, Vibe Coding
  affiliation: Postdoc @ National University of Singapore
  github: deciding
  twitter: zhangzn710
  zhihu: zhangzn-49-6

show_excerpts: true
